# How to configure this file
# https://github.com/aquasecurity/tfsec/blob/master/docs/guides/configuration/config.md

# TODO Pass this file to a repository to have it always updated and synced cross projects
exclude:
  - aws-s3-enable-bucket-logging
  - aws-s3-enable-versioning

severity_overrides:
  aws-s3-encryption-customer-key: LOW
